version = 2

[[builds]]
  src = "MainApp.js"
  use = "@vercel/node"

[[routes]]
  src = "/(.*)"
  dest = "/MainApp.js"

  [[redirects]]
  from = "/*"
  to = "/.netlify/functions/MainApp" # Jika MainApp adalah fungsi
  status = 200
